server:
  port: 7901
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
spring:
  application:
    name: eva-web-mis
  redis:
    host: 119.23.149.69
    port: 6379
    password: test123
    pool:
      max-active: 300
      max-idle: 100
      min-idle: 1
      max-wait: 10000
    timeout: 20
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  config: classpath:config/logback-spring.xml
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:7801/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC
      lilizhou: BBC
    lease-renewal-interval-in-seconds: 5
feign:
  compression:
    request:
      enabled: false
      mime-types: text/xml;application/xml;application/json
      min-request-size: 2048
    response:
      enabled: true